{% set version = "2.2.4" %}

package:
  name: astroid
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/astroid/astroid-{{ version }}.tar.gz
  sha256: 62bd1d8d2ace3e812b3a22eb3c4b7856536d8cc0cdb37466f6a53cf881dbad1f

build:
  number: 0
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - setuptools
    - lazy-object-proxy
    - six
    - wrapt
    - typed-ast   # [py<37]
    - typing      # [py<35]

test:
  imports:
    - astroid
    - astroid.modutils

about:
  home: https://www.astroid.org/
  license: LGPL 2.1
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: 'A abstract syntax tree for Python with inference support.'
  description: |
    Astroid provide a common base representation of python source code for
    projects such as pychecker, pyreverse, pylint.
  doc_url: http://astroid.readthedocs.io/en/latest/?badge=latest
  doc_source_url: https://github.com/PyCQA/astroid/blob/master/doc/index.rst
  dev_url: https://github.com/PyCQA/astroid

extra:
  recipe-maintainers:
    - ericdill
    - jakirkham
    - jjhelmus
    - ocefpaf
