{% set version = "2.12.2" %}

package:
  name: astroid
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/astroid/astroid-{{ version }}.tar.gz
  sha256: 4675ef501edbbb143b3d9bb4c81d5f6338f08f960beed2ce41a03dc4cd20d777

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
    # the setuptools version needs to be compatible with version 62
    - setuptools >=62.6,<63.0.0
    # the wheel version needs to be compatible with version 0.37
    - wheel >=0.37.1,<0.38.0
  run:
    - python
    - setuptools >=62.6,<63.0.0
    - lazy-object-proxy >=1.4.0
    - wrapt >=1.11,<2
    - typed-ast >=1.4.0,<2.0  # [py<38]
    - typing-extensions >=3.10 # [py<310]

test:
  requires:
    - pip
  imports:
    - astroid
    - astroid.modutils
  commands:
    - python -m pip check

about:
  home: https://www.astroid.org/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: A abstract syntax tree for Python with inference support.
  description: |
    Astroid provide a common base representation of python source code for
    projects such as pychecker, pyreverse, pylint.
  doc_url: https://pylint.pycqa.org/projects/astroid/en/latest/?badge=latest
  doc_source_url: https://github.com/PyCQA/astroid/blob/master/doc/index.rst
  dev_url: https://github.com/PyCQA/astroid

extra:
  recipe-maintainers:
    - ericdill
    - jakirkham
    - jjhelmus
    - ocefpaf
