{% set name = "astroid" %}
{% set version = "1.5.3" %}
{% set sha256 = "492c2a2044adbf6a84a671b7522e9295ad2f6a7c781b899014308db25312dd35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - enum34  # [py2k]
    - singledispatch  # [py2k]
    - backports.functools_lru_cache  # [py2k]
    - six
    - lazy-object-proxy
    - wrapt

test:
  imports:
    - astroid
    - astroid.tests
    # import modutils to expose the setuptools runtime requirement
    - astroid.modutils

about:
  home: https://www.astroid.org/
  license: LGPL 2.1
  license_family: LGPL
  license_file: COPYING
  summary: 'A abstract syntax tree for Python with inference support.'
  description: |
    Astroid provide a common base representation of python source code for
    projects such as pychecker, pyreverse, pylint.
  doc_url: http://astroid.readthedocs.io/en/latest/?badge=latest
  doc_source_url: https://github.com/PyCQA/astroid/blob/master/doc/index.rst
  dev_url: https://github.com/PyCQA/astroid

extra:
  recipe-maintainers:
    - ericdill
    - jakirkham
