{% set version = "2.14.2" %}

package:
  name: astroid
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/astroid/astroid-{{ version }}.tar.gz
  sha256: a3cf9f02c53dd259144a7e8f3ccd75d67c9a8c716ef183e0c1f291bc5d7bb3cf
build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.7.2
    - lazy-object-proxy >=1.4.0
    - wrapt >=1.14,<2  # [py>=311]
    - wrapt >=1.11,<2  # [py<311]
    - typed-ast >=1.4.0,<2.0  # [py<38]
    - typing-extensions >=4.0.0 # [py<311]

test:
  requires:
    - pip
  imports:
    - astroid
    - astroid.brain
    - astroid.interpreter
    - astroid.nodes
    - astroid.modutils
  commands:
    - python -m pip check

about:
  home: https://github.com/PyCQA/astroid
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: A abstract syntax tree for Python with inference support.
  description: |
    Astroid provide a common base representation of python source code for
    projects such as pychecker, pyreverse, pylint.
  doc_url: https://pylint.pycqa.org/projects/astroid/en/latest/?badge=latest
  dev_url: https://github.com/PyCQA/astroid

extra:
  recipe-maintainers:
    - ericdill
    - jakirkham
    - jjhelmus
    - ocefpaf
