{% set name = "astroid" %}
{% set version = "3.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astroid-{{ version }}.tar.gz
  sha256: a88c7994f914a4ea8572fac479459f4955eeccc877be3f2d959a33273b0cf40b

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - typing-extensions >=4.0.0  # [py<311]

test:
  requires:
    - pip
    - pytest
  imports:
    - astroid
    - astroid.brain
    - astroid.interpreter
    - astroid.nodes
    - astroid.modutils
  source_files:
    - tests
  commands:
    - pip check
    # Skip tests that require manipulating file system and recursion limits in unsafe ways.
    - pytest -v tests -k "not (test_data_build_error_filename or test_recursion_error_trapped)"

about:
  home: https://github.com/PyCQA/astroid
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: A abstract syntax tree for Python with inference support.
  description: |
    Astroid provide a common base representation of python source code for
    projects such as pychecker, pyreverse, pylint.
  doc_url: https://pylint.pycqa.org/projects/astroid/en/latest/?badge=latest
  dev_url: https://github.com/PyCQA/astroid

extra:
  skip-lints:
    - invalid_url
  recipe-maintainers:
    - ericdill
    - jakirkham
    - jjhelmus
    - ocefpaf