{% set name = "astroid" %}
{% set version = "3.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/astroid-{{ version }}.tar.gz
  sha256: 1e5a5011af2920c7c67a53f65d536d65bfa7116feeaf2354d8b94f29573bb0ce

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=77
  run:
    - python
    - typing-extensions >=4  # [py<311]

test:
  source_files:
    - tests
  imports:
    - astroid
    - astroid.arguments
    - astroid.astroid_manager
    - astroid.bases
    - astroid.brain
    - astroid.builder
    - astroid.const
    - astroid.context
    - astroid.decorators
    - astroid.exceptions
    - astroid.filter_statements
    - astroid.inference_tip
    - astroid.interpreter
    - astroid.manager
    - astroid.modutils
    - astroid.nodes
    - astroid.objects
    - astroid.raw_building
    - astroid.transforms
    - astroid.typing
    - astroid.util
  requires:
    - pip
    - pytest
    - mypy
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Skip tests that require manipulating file system and recursion limits in unsafe ways.
    - pytest -v tests -k "not (test_data_build_error_filename or test_recursion_error_trapped)"

about:
  home: https://github.com/PyCQA/astroid
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: A abstract syntax tree for Python with inference support.
  description: |
    Astroid provide a common base representation of python source code for
    projects such as pychecker, pyreverse, pylint.
  doc_url: https://pylint.pycqa.org/projects/astroid/en/latest/?badge=latest
  dev_url: https://github.com/PyCQA/astroid

extra:
  skip-lints:
    - invalid_url
  recipe-maintainers:
    - ericdill
    - jakirkham
    - jjhelmus
    - ocefpaf
