travis:
  secure:
    BINSTAR_TOKEN: bLX+4fB4JfPwpYOm4nHlozE5IDsI1hItEGL51EJ6UkQ960ATczbgKHj8wDO+NhXFnOkvztVasnXLpyWTySbTmLJk3/3Ch5/Vqjfu31J2gp/kUnGDRE/UsJGeneRfRB76lpa12FdK5W7jqs790zIklyB353vad8uoW0ZAAAD1VOwHmujlK8C14Nph8qz+fTPxqAavpdNc/vLqZA0s3YmhuzE1ZlnbNJ6LBFpIv8YIpKZKaYDlvo8jdHinrNDr71YdHEPAm4hOI1YdTpVGD3uXpAscP87uCocUTEG3WlsMTWcs9HdDlx+dxTDZDelcAKAxuHSp1A9+bCiFdCCm63F2z9MUcgcvHlBekVTuEF19Lx0mMNMLTcrBlA4evKYzMY05pg4V3Dj6lP2cnQMV2ah7OBECPmNlVB3DqaPWBqVz9qaS6hLIjqJ4EBgEA5tKME+kD+9LPKN72JTsmf8my9Wdqamq4m3pXXmBM+GARYx2m7XNYFhsa1GqjA6/RQu6Ga0h0vhPknhEFww0T4PWZAtLR+/tkaoOSGb/XvuYY4lp7exPy5V5CPBXj+6CZImbp+X2zvhTs6ugeaPR+SKs5Xu+YDosid2nX71rscT8BqJp6hCPwTy6ywBje9+UWlTDXOu3zuq/kwPai+Ib8XYo3+B933ojnrc/WmdP/J3SBGh9/no=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
