travis:
  secure:
    BINSTAR_TOKEN: X5y9p8ukI2mmvp2fNQzNO6gkVi211cc4jLlrLp14Smolt/+dXKRu1IA28HlVNBkHXQzA6LnfJInIs0ulAdXPj2JW4EXtWn5IPcobITwY2wl0SBZx76Icb5LbD2qlJ1ryKoV0EItC5MaRT0owqvDK/nt1pnGlST+JAd3KK2uL4wD8elQtiLxa1T3Vd/z5/3SAX8sHjZoIj4HYX9maJuMXJr4cIWn29h2Qx9fP3ypgSaodYzHLiLr9ZhYSIJwq73xlNpYbi18gXqnZXYlHS4eewA3suBUkr4uENlQ3HJMn+q8oWfftsRQ0QMU7nyjCr3mqg7W2h00KcnrEZD1IvlaWDI1uq7a0gkx8bLSQuliHVxAcj0yqepEyDXxNP2sZYxx9VzkXGFfTKxL6P6GPOxGzMC2Lboy9yhpkag+FNW52+PZGM4ROXqvXv8Ds8MI4sFeMn3GwoGVw5oZlzVefAilFVkc9vHGKya2zhqg9STO6J7a9/k5gB9sDSFOmN8QFK1Ktjlby7+1+7iefBR4UOeQMV5zyryzKhTwqHasuSRhXCJSryKWrkpie4ZphgQgFHCaYrdl7zN+xwTWanLC2vgPLHrOVAusqEMgbnE+Qg5aCowc7pEE5cleLVNaiMmy/06A7F2pL7iJE4He6gCjWqVPS2NF05oYCNuk1H7Rz0HUoV2o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
